exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: JCOP
subtitle: "JCOP"
url: "" # the base hostname & protocol for your site
baseurl: "/jcopweb"
logo: "/assets/img/logo.jpg"

# Build settings
markdown: kramdown